##===================================================================================================================
## Makefile -- wrapper for tup to make the assembler executable
##
##      Copyright (c) 2023-2024 - Adam Clark
##      License: Beerware
##
##	Other targets will be added here to perform other functions.
##
##      Date     Tracker  Version  Description
##  -----------  -------  -------  ---------------------------------------------------------------------------------
##  2023-Feb-28  Initial  v0.0.1   Initial Version
##===================================================================================================================


all:
	tup


