name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'    
    - name: ls Qt
      run: ls -al Qt
    - name: Install tup
      run: sudo apt install tup
    - name: Initialize tup
      run: tup init
    - name: Build everything
      run: make
