name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
    - name: Make a local bin folder
      run: mkdir -p ~/bin
    - name: Link to the 16bcfs.arch file
      run: ln -s ~/work/16bcfs/16bcfs/asm/arch ~/bin/arch
    - name: Install tup
      run: sudo apt install tup
    - name: Initialize tup
      run: tup init
    - name: Build everything
      run: make
    - name: Check Test `asm-00001`
      run: diff 16bcfs-tests/asm-00001/expected.txt 16bcfs-tests/asm-00001/output.txt
    - name: Check Test `asm-00002`
      run: diff 16bcfs-tests/asm-00002/expected.txt 16bcfs-tests/asm-00002/output.txt
    - name: Check Test `asm-00003`
      run: diff 16bcfs-tests/asm-00003/expected.txt 16bcfs-tests/asm-00003/output.txt
