name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.0'
    - name: Make a local bin folder
      run: mkdir -p ~/bin
    - name: Link to the 16bcfs.arch file
      run: ln -s asm/arch ~/bin/arch
    - name: where is home?
      run: echo ~
    - name: exports
      run: export
    - name: pwd
      run: pwd
    - name: ls Qt
      run: ls -alR ../Qt/6.6.0/gcc_64/libexec
    - name: Install tup
      run: sudo apt install tup
    - name: Initialize tup
      run: tup init
    - name: Build everything
      run: make
